@startuml
left to right direction

actor Customer
actor Restaurant

rectangle "Online Order System" {
  (Sign Up)
  (Login)
  (Browse Restaurant)
  (Add to Cart)
  (Checkout Order)
}

Customer --> (Sign Up)
Customer --> (Login)
Customer --> (Browse Restaurant)
Customer --> (Add to Cart)
Customer --> (Checkout Order)

(Browse Restaurant) .> (Login) : <<include>>
(Add to Cart) .> (Login) : <<include>>
(Checkout Order) .> (Login) : <<include>>

Restaurant -- (Checkout Order)

@enduml
